import type { NextPage } from 'next'
import MovieList from "../components/MovieList";
import Nav from "../components/Nav";
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-slate-700 text-white">Hello ContextApi</div>
        <Nav />
        <MovieList />
      </main>
    </>
  );
}

export default Home
